spring.application.name=pzm_iroute

# Conexion a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_route?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Guayaquil
spring.datasource.username=root
spring.datasource.password=

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Spring Batch
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# Puerto
server.port=8080